import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/custom/Navbar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + cn(" flex flex-col justify-start items-center w-full min-h-screen gap-4", "bg-zinc-400")
        }
      >
        <Navbar />
        <div className="flex flex-col justify-center items-start h-full w-full p-4">{children}</div>
      </body>
    </html>
  );
}
